# -*- coding: utf-8 -*-
"""People detection and counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRzWeM4ortoiE3mFVpqCcmD4K_CMFZYv
"""

!pip install --upgrade ultralytics

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ta18Dp4JpDievmIAMw6P")
project = rf.workspace("titulacin").project("person-detection-9a6mk")
version = project.version(6)
dataset = version.download("yolov8")

from ultralytics import YOLO

# Load a pretrained YOLO model
# The model file is downloaded as part of the dataset from Roboflow
model = YOLO(f"{dataset.location}/yolov8s.pt")  # You can choose a different YOLO model like yolov8s.pt, yolov8m.pt, etc.

# Train the model with resumable training enabled
# The 'resume=True' argument will automatically resume from the last saved checkpoint
# if training is interrupted.
results = model.train(data=f"{dataset.location}/data.yaml", epochs=25, imgsz=500)

print("Training finished.")

# Run the training cell to define and load the model
get_ipython().run_cell('1UqUnJ51sWE-')

from google.colab import files
uploaded = files.upload()

results = model.predict(source="sample image 3.jpg", conf=0.25)
results[0].show()
num_people = len(results[0].boxes)
print(f"Number of people detected: {num_people}")

